version: '3.5'
services:

  postgres:
    container_name: ob_postgres
    image: postgres:latest
    env_file: ../src/.env
    ports:
      - 5432:5432
    volumes:
      - ./db_volume:/var/lib/postgresql/data
  
  web:
    build:
      context: ../.
      dockerfile: ./docker/web/Dockerfile
    restart: always
    container_name: ob_web
    command: gunicorn --bind 0.0.0.0:8000 app.wsgi:application
    env_file: ../src/.env
    volumes:
      - ../src/static:/src/static/
    ports:
      - 8000:8000
    depends_on:
      - postgres

volumes:
  db_volume: