# Generated by Django 4.0 on 2022-09-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicd', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='repo',
            constraint=models.UniqueConstraint(fields=('owner', 'repository'), name='unique_parameter_for_repository'),
        ),
    ]
